services:
  db:
    image: postgres
    container_name: cnl-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - 5432:5432
    networks:
      - cnl
    restart: unless-stopped
    profiles:
      - local

  maildev:
    image: maildev/maildev
    container_name: cnl-maildev
    ports:
      - 1080:1080
      - 1025:1025
    profiles:
      - local

  localstack:
    container_name: cnl-localstack
    image: localstack/localstack
    ports:
      - 4566:4566            # LocalStack Gateway
    environment:
      - SERVICES=s3
    volumes:
      - ./localstack-bootstrap:/etc/localstack/init/ready.d
    profiles:
      - local

networks:
  cnl:
    driver: bridge