server:
  error:
    include-message: always
  servlet:
    context-path: /api/${app.config.api-version}/

spring:
  profiles:
    active: dev
  application:
    name: cookandlaughbe
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/appdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://www.googleapis.com
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
  servlet:
    multipart:
      max-file-size: 1MB
  liquibase:
    enabled: true # Disable it to manage migrations manually. It'll allow to execute rollbacks manually.

springdoc:
  default-produces-media-type: application/json

app:
  domain:
    root: cookandlaugh.com.ua
  config:
    api-version: v1
  security:
    cors:
      allowed-origins: ${ALLOWED_ORIGINS}
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: ${ALLOWED_HEADERS}
      exposed-headers: ${EXPOSED_HEADERS}
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      token-prefix: "Bearer "
      token-expiration-days: 7
    registration:
      activation-code:
        expiration-minutes: 15
        confirmation-url: http://localhost:4200/confirm-registration
