spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: user
    password: password
  mail:
    host: localhost
    port: 1025
    username: username
    password: password
    properties:
      mail:
        smtp:
          trust: "*"

app:
  security:
    cors:
      allowed-origins: http://localhost:5173
      allowed-headers: "*"
      exposed-headers: "*"
    jwt:
      secret-key: VmVyeUxvbmdBbmRWZXJ5U2VjcmV0S2V5U3RyaW5nVmVyeUxvbmdBbmRWZXJ5U2VjcmV0S2V5U3RyaW5n
