server:
  error:
    include-message: always

app:
  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    exposed-headers: "*"

spring:
  application:
    name: cookandlaughbe
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/appdb
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
