name: Run Maven Tests

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  maven-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up GraalVM 22
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'graalvm'
          java-version: '22'
      - name: Test
        run: mvn test -B